import { test } from 'node:test';
import assert from 'node:assert/strict';
import { functions as F, registerFunction, parseDate, formatDate, toISODate, namespaces, methods, parsePuncExample } from '../engine/functions.js';
import { evaluate } from '../engine/expr.js';

test('text functions', () => {
  assert.equal(F.upper('abc'), 'ABC');
  assert.equal(F.lower('ABC'), 'abc');
  assert.equal(F.title('john o\'neil-smith van der berg'), 'John O\'Neil-Smith Van Der Berg');
  assert.equal(F.capitalize('hello world'), 'Hello world');
  assert.equal(F.trim('  x  '), 'x');
  assert.equal(F.initials('john ronald reuel tolkien'), 'JRRT');
  assert.equal(F.initials('Mary-Kate Olsen'), 'MKO');
  assert.equal(F.possessive('James'), "James'");
  assert.equal(F.possessive('Mary'), "Mary's");
  assert.equal(F.len('abc'), 3);
  assert.equal(F.length([1, 2]), 2);
  assert.equal(F.contains('Hello World', 'world'), true);
  assert.equal(F.contains(['a', 'b'], 'b'), true);
  assert.equal(F.contains(null, 'b'), false);
  assert.equal(F.startswith('Hello', 'he'), true);
  assert.equal(F.endswith('Hello', 'LO'), true);
  assert.equal(F.replace('a-b-c', '-', '+'), 'a+b+c');
  assert.equal(F.nbsp(), ' ');
  assert.equal(F.blank(), '');
  assert.equal(F.initcap('jOHN'), 'JOHN');
  assert.equal(F.initcap('jOHN', true), 'John');
  assert.equal(F.titlecaps('a tale'), 'A Tale');
  for (const fn of ['upper', 'lower', 'title', 'capitalize', 'trim', 'initials', 'possessive', 'replace', 'initcap']) {
    assert.equal(F[fn](undefined), '', fn);
    assert.equal(F[fn](null), '', fn);
  }
});

test('currency and number', () => {
  assert.equal(F.currency(1234.5), '$1,234.50');
  assert.equal(F.currency(-1234.5), '-$1,234.50');
  assert.equal(F.currency(0), '$0.00');
  assert.equal(F.currency('1,234.5'), '$1,234.50');
  assert.equal(F.currency('$1,234.5'), '$1,234.50');
  assert.equal(F.currency(1234.5, '€', 0), '€1,235');
  assert.equal(F.currency(1234.5, { symbol: '£', decimals: 1 }), '£1,234.5');
  assert.equal(F.currency(undefined), '');
  assert.equal(F.currency('abc'), '');
  assert.equal(F.number(1234567.891), '1,234,567.891');
  assert.equal(F.number(1234567.891, 2), '1,234,567.89');
  assert.equal(F.number(1000, 0), '1,000');
  assert.equal(F.number(-1234.5, 1), '-1,234.5');
  assert.equal(F.number(null), '');
  assert.equal(F.round(2.345, 2), 2.35);
  assert.equal(F.round(2.5), 3);
  assert.equal(F.abs(-3), 3);
  assert.equal(F.min(3, 1, 2), 1);
  assert.equal(F.max([3, 1, 2]), 3);
  assert.equal(F.min(), '');
});

test('words / dollars / ordinals', () => {
  assert.equal(F.words(0), 'zero');
  assert.equal(F.words(7), 'seven');
  assert.equal(F.words(15), 'fifteen');
  assert.equal(F.words(42), 'forty-two');
  assert.equal(F.words(100), 'one hundred');
  assert.equal(F.words(1234), 'one thousand two hundred thirty-four');
  assert.equal(F.words(1000000), 'one million');
  assert.equal(F.words(1234567), 'one million two hundred thirty-four thousand five hundred sixty-seven');
  assert.equal(F.words(-5), 'minus five');
  assert.equal(F.words(1234.56), 'one thousand two hundred thirty-four');
  assert.equal(F.words(undefined), '');
  assert.equal(F.cardinal(123), 'one hundred twenty-three');
  assert.equal(F.dollars(1234.56), 'One Thousand Two Hundred Thirty-Four and 56/100 Dollars');
  assert.equal(F.dollars(10000), 'Ten Thousand and 00/100 Dollars');
  assert.equal(F.dollarsWords(1234.56), 'One Thousand Two Hundred Thirty-Four Dollars and 56/100');
  assert.equal(F.dollarsWords(1), 'One Dollar and 00/100');
  assert.equal(F.dollarsFull(10000), 'Ten Thousand Dollars ($10,000.00)');
  assert.equal(F.dollarsFull(9.12), 'Nine Dollars and Twelve Cents ($9.12)');
  assert.equal(F.dollarsAndCents(50.1), 'Fifty Dollars and Ten Cents');
  assert.equal(F.cents(12.34), 34);
  assert.equal(F.cents(0.999), 0); // rounds up to next dollar
  assert.equal(F.dollars(0.999), 'One and 00/100 Dollars');
  assert.equal(F.dollars(''), '');
  assert.equal(F.cardinalcur(50.1, 'dollars', 'cents'), 'Fifty Dollars and Ten Cents');
  assert.equal(F.cardinalcur(1.01, 'euros', 'cents'), 'One Euro and One Cent');
  assert.equal(F.cardinaldec(12.35, 2), 'twelve point three five');
  assert.equal(F.cardinaldec(3), 'three');
  assert.equal(F.ordinal(1), '1st');
  assert.equal(F.ordinal(2), '2nd');
  assert.equal(F.ordinal(3), '3rd');
  assert.equal(F.ordinal(4), '4th');
  assert.equal(F.ordinal(11), '11th');
  assert.equal(F.ordinal(12), '12th');
  assert.equal(F.ordinal(13), '13th');
  assert.equal(F.ordinal(21), '21st');
  assert.equal(F.ordinal(111), '111th');
  assert.equal(F.ordinal(122), '122nd');
  assert.equal(F.ordinal(null), '');
  assert.equal(F.ordsuffix(22), 'nd');
  assert.equal(F.ordinalwords(1), 'first');
  assert.equal(F.ordinalwords(2), 'second');
  assert.equal(F.ordinalwords(3), 'third');
  assert.equal(F.ordinalwords(5), 'fifth');
  assert.equal(F.ordinalwords(8), 'eighth');
  assert.equal(F.ordinalwords(9), 'ninth');
  assert.equal(F.ordinalwords(12), 'twelfth');
  assert.equal(F.ordinalwords(20), 'twentieth');
  assert.equal(F.ordinalwords(22), 'twenty-second');
  assert.equal(F.ordinalwords(100), 'one hundredth');
  assert.equal(F.ordinalwords(101), 'one hundred first');
  assert.equal(F.ordinalword(23), 'twenty-third');
  assert.equal(F.roman(1994), 'MCMXCIV');
  assert.equal(F.roman(4), 'IV');
  assert.equal(F.roman(0), '');
  assert.equal(F.alpha(1), 'a');
  assert.equal(F.alpha(26), 'z');
  assert.equal(F.alpha(27), 'aa');
  assert.equal(F.alpha(28, true), 'AB');
});

test('date parsing is local-date-only (no timezone shift)', () => {
  const d = parseDate('2026-03-05');
  assert.equal(d.getFullYear(), 2026);
  assert.equal(d.getMonth(), 2);
  assert.equal(d.getDate(), 5);
  assert.equal(toISODate(parseDate('3/5/2026')), '2026-03-05');
  assert.equal(toISODate(parseDate('03/05/26')), '2026-03-05');
  assert.equal(toISODate(parseDate('March 5, 2026')), '2026-03-05');
  assert.equal(toISODate(parseDate('Mar 5 2026')), '2026-03-05');
  assert.equal(toISODate(parseDate('5 March 2026')), '2026-03-05');
  assert.equal(toISODate(parseDate(new Date(2026, 2, 5, 23, 59))), '2026-03-05');
  assert.equal(toISODate(parseDate('2026-03-05T00:00:00.000Z')), '2026-03-05');
  assert.equal(parseDate('2026-02-30'), null);
  assert.equal(parseDate('not a date'), null);
  assert.equal(parseDate(''), null);
  assert.equal(parseDate(undefined), null);
  // 1000 consecutive days round-trip without drift
  let cur = new Date(2024, 0, 1);
  for (let i = 0; i < 1000; i++) {
    const iso = toISODate(cur);
    assert.equal(toISODate(parseDate(iso)), iso);
    cur = F.addDays(cur, 1);
  }
});

test('formatDate tokens and presets', () => {
  const d = '2026-03-05';
  assert.equal(formatDate(d, 'long'), 'March 5, 2026');
  assert.equal(formatDate(d), 'March 5, 2026');
  assert.equal(formatDate(d, 'short'), '3/5/2026');
  assert.equal(formatDate(d, 'legal'), 'the 5th day of March, 2026');
  assert.equal(formatDate(d, 'iso'), '2026-03-05');
  assert.equal(formatDate(d, 'medium'), 'Mar 5, 2026');
  assert.equal(formatDate(d, 'full'), 'Thursday, March 5, 2026');
  assert.equal(formatDate(d, 'yyyy yy MMMM MMM MM M dd d EEEE EEE'), '2026 26 March Mar 03 3 05 5 Thursday Thu');
  assert.equal(formatDate(d, 'YYYY YY MMMM MMM MM M DD D Do E dddd ddd'), '2026 26 March Mar 03 3 05 5 5th Thu Thursday Thu');
  assert.equal(formatDate('2026-06-03', 'Do \\[day of\\] MMMM YYYY'), '3rd day of June 2026');
  assert.equal(formatDate('2026-06-03', 'Do [day of] MMMM, YYYY'), '3rd day of June, 2026');
  assert.equal(formatDate(d, "'on' MMMM d"), 'on March 5');
  assert.equal(formatDate(d, 'MM/dd/yyyy'), '03/05/2026');
  assert.equal(formatDate(d, 'd MMMM yyyy'), '5 March 2026');
  assert.equal(formatDate(undefined, 'long'), '');
  assert.equal(formatDate('garbage', 'long'), '');
  assert.equal(formatDate(new Date(2026, 11, 25), 'EEE, MMM d'), 'Fri, Dec 25');
});

test('format-by-example: dates', () => {
  const d = '1990-06-03';
  assert.equal(F.format(d, 'June 3, 1990'), 'June 3, 1990');
  assert.equal(F.format('2026-12-25', 'June 3, 1990'), 'December 25, 2026');
  assert.equal(F.format(d, '3 June 1990'), '3 June 1990');
  assert.equal(F.format(d, '06/03/1990'), '06/03/1990');
  assert.equal(F.format(d, '6/3/90'), '6/3/90');
  assert.equal(F.format(d, 'June 3rd, 1990'), 'June 3rd, 1990');
  assert.equal(F.format(d, '3rd day of June, 1990'), '3rd day of June, 1990');
  assert.equal(F.format(d, 'Monday, June 3, 1990'), 'Sunday, June 3, 1990');
  assert.equal(F.format(d, '1990-06-03'), '1990-06-03');
  assert.equal(F.format('2026-01-09', 'Jun 3, 1990'), 'Jan 9, 2026');
  assert.equal(F.format('2026-01-09', '06/03/1990'), '01/09/2026');
  assert.equal(F.format(d, 'legal'), 'the 3rd day of June, 1990');
});

test('format-by-example: numbers and text, numeral patterns, booleans', () => {
  assert.equal(F.format(1234.5, '9,999.00'), '1,234.50');
  assert.equal(F.format(1234.5, '9999'), '1235');
  assert.equal(F.format(1234.5, '$9,999.00'), '$1,234.50');
  assert.equal(F.format(0.256, '9,999.99%'), '25.60%');
  assert.equal(F.format(9, 'nine'), 'nine');
  assert.equal(F.format(23, 'Nine'), 'Twenty-Three');
  assert.equal(F.format(9, 'NINE'), 'NINE');
  assert.equal(F.format(22, '3rd'), '22nd');
  assert.equal(F.format(22, 'third'), 'twenty-second');
  assert.equal(F.format(22, 'Third'), 'Twenty-Second');
  assert.equal(F.format(9.12, 'Nine Dollars and Twelve Cents'), 'Nine Dollars and Twelve Cents');
  assert.equal(F.format(1234.56, 'Nine Dollars and 9/100'), 'One Thousand Two Hundred Thirty-Four Dollars and 56/100');
  assert.equal(F.format(1234.56, 'nine dollars and 9/100'), 'one thousand two hundred thirty-four dollars and 56/100');
  assert.equal(F.format(1234.56, 'Nine and 9/100 Dollars'), 'One Thousand Two Hundred Thirty-Four and 56/100 Dollars');
  assert.equal(F.format(1234.5, '0,0.00'), '1,234.50');
  assert.equal(F.format(1234.5, '0,0'), '1,235');
  assert.equal(F.format(1234.5, '0.00'), '1234.50');
  assert.equal(F.format(1234.56789, '0,0.0000'), '1,234.5679');
  assert.equal(F.format(0.5, '0%'), '50%');
  assert.equal(F.format('hello world', 'LIKE THIS'), 'HELLO WORLD');
  assert.equal(F.format('hello world', 'Like This'), 'Hello World');
  assert.equal(F.format('HELLO', 'like this'), 'hello');
  assert.equal(F.format(true, 'heads', 'tails'), 'heads');
  assert.equal(F.format(false, 'heads', 'tails'), 'tails');
  assert.equal(F.format(true), 'Yes');
  assert.equal(F.format(undefined, '0.00'), '');
  assert.equal(evaluate('Flag|format:"heads":"tails"', { Flag: false }), 'tails');
  assert.equal(evaluate('Fee|format:"0,0.00"', { Fee: 1234.5 }), '1,234.50');
});

test('date math', () => {
  assert.equal(toISODate(F.addDays('2026-01-31', 1)), '2026-02-01');
  assert.equal(toISODate(F.addDays('2026-03-01', -1)), '2026-02-28');
  assert.equal(toISODate(F.addMonths('2026-01-31', 1)), '2026-02-28');
  assert.equal(toISODate(F.addMonths('2026-01-15', 13)), '2027-02-15');
  assert.equal(toISODate(F.addYears('2024-02-29', 1)), '2025-02-28');
  assert.equal(F.yearsBetween('2000-06-15', '2026-06-14'), 25);
  assert.equal(F.yearsBetween('2000-06-15', '2026-06-15'), 26);
  assert.equal(F.yearsBetween('2026-06-15', '2000-06-15'), -26);
  assert.equal(typeof F.age('2000-01-01'), 'number');
  assert.equal(F.dateDiffDays('2026-01-01', '2026-03-01'), 59);
  assert.equal(F.dateDiffDays('2026-03-01', '2026-01-01'), -59);
  assert.equal(F.year('2026-03-05'), 2026);
  assert.equal(F.month('2026-03-05'), 3);
  assert.equal(F.day('2026-03-05'), 5);
  assert.equal(F.monthName('2026-03-05'), 'March');
  assert.equal(F.weekday('2026-03-05'), 'Thursday');
  assert.equal(F.addDays(undefined, 1), '');
  assert.equal(F.year(''), '');
  const t = F.today();
  assert.equal(t.getHours(), 0);
  assert.equal(namespaces.date.monthsBetween('2026-01-31', '2026-02-28'), 0);
  assert.equal(namespaces.date.monthsBetween('2026-01-01', '2026-03-01'), 2);
});

test('pluralize / join / punc / pronoun / grammar helpers', () => {
  assert.equal(F.pluralize(1, 'child', 'children'), '1 child');
  assert.equal(F.pluralize(3, 'child', 'children'), '3 children');
  assert.equal(F.pluralize(0, 'child', 'children'), '0 children');
  assert.equal(F.pluralize(2, 'box'), '2 boxes');
  assert.equal(F.pluralize(2, 'party'), '2 parties');
  assert.equal(F.pluralize([1, 2], 'item'), '2 items');
  assert.equal(F.pluralize(2, 'child', 'children', true), 'children');
  assert.equal(F.join(['A', 'B', 'C']), 'A, B, and C');
  assert.equal(F.join(['A', 'B']), 'A and B');
  assert.equal(F.join(['A']), 'A');
  assert.equal(F.join([]), '');
  assert.equal(F.join(undefined), '');
  assert.equal(F.join(['A', 'B', 'C'], 'or'), 'A, B, or C');
  assert.equal(F.join(['A', 'B', 'C'], 'and', false), 'A, B and C');
  assert.equal(F.join(['A', 'B', 'C'], ''), 'A, B, C');
  assert.equal(F.join(['A', '', null, 'C']), 'A and C');
  assert.equal(F.join([{ Name: 'x' }]), '[object Object]'.length ? F.join([{ Name: 'x' }]) : '');
  assert.deepEqual(parsePuncExample('1, 2, and 3'), { sep: ', ', lastSep: ', and ', twoSep: ' and ', suffix: '' });
  assert.deepEqual(parsePuncExample('1, 2 and 3.'), { sep: ', ', lastSep: ' and ', twoSep: ' and ', suffix: '.' });
  assert.deepEqual(parsePuncExample('1; 2; or 3'), { sep: '; ', lastSep: '; or ', twoSep: ' or ', suffix: '' });
  assert.equal(parsePuncExample('1 and 2').twoSep, ' and ');
  assert.equal(F.punc(['A', 'B', 'C'], '1, 2, and 3'), 'A, B, and C');
  assert.equal(F.punc(['A', 'B', 'C'], '1, 2 and 3.'), 'A, B and C.');
  assert.equal(F.punc(['A', 'B'], '1; 2; or 3'), 'A or B');
  assert.equal(F.punc(['A'], '1, 2, and 3.'), 'A.');
  assert.equal(F.punc(['A', 'B', 'C']), 'A, B, and C');
  assert.equal(F.punc(['A', 'B', 'C'], 'or'), 'A, B, or C');
  assert.equal(F.pronoun('female', 'subject'), 'she');
  assert.equal(F.pronoun('male', 'object'), 'him');
  assert.equal(F.pronoun('M', 'possessive'), 'his');
  assert.equal(F.pronoun('female', 'possessiveadj'), 'her');
  assert.equal(F.pronoun('female', 'possessive'), 'hers');
  assert.equal(F.pronoun('female', 'reflexive'), 'herself');
  assert.equal(F.pronoun('nonbinary', 'subject'), 'they');
  assert.equal(F.pronoun('', 'object'), 'them');
  assert.equal(F.pronoun('neutral', 'possessive'), 'theirs');
  assert.equal(F.pronoun('neutral', 'possessiveadj'), 'their');
  assert.equal(F.pronoun('neutral', 'reflexive'), 'themselves');
  assert.equal(F.pronoun('she'), 'she');
  assert.equal(F.isAre(1), 'is');
  assert.equal(F.isAre([1, 2]), 'are');
  assert.equal(F.isAre(0), 'are');
  assert.equal(F.hasHave(1), 'has');
  assert.equal(F.hasHave(3), 'have');
  assert.equal(F.doesDo(1), 'does');
  assert.equal(F.doesDo(2), 'do');
  assert.equal(F.wasWere(1), 'was');
  assert.equal(F.wasWere([]), 'were');
  assert.equal(F.article('apple'), 'an');
  assert.equal(F.article('house'), 'a');
  assert.equal(F.article('hour'), 'an');
  assert.equal(F.article('uniform'), 'a');
  assert.equal(F.article(''), '');
  assert.equal(F.plural('child'), 'children');
  assert.equal(F.plural('Child'), 'Children');
  assert.equal(F.plural('entity'), 'entities');
  assert.equal(F.plural('box'), 'boxes');
  assert.equal(F.plural('church'), 'churches');
  assert.equal(F.plural('wife'), 'wives');
  assert.equal(F.plural('trustee'), 'trustees');
  assert.equal(F.plural('day'), 'days');
  assert.equal(F.plural('entity', 1), 'entity');
  assert.equal(F.plural('entity', 2), 'entities');
  assert.equal(F.quantity(3, 'heir'), '3 heirs');
  assert.equal(F.quantity(1, 'child'), '1 child');
  assert.equal(F.quantity([1, 2, 3], 'beneficiary'), '3 beneficiaries');
  assert.equal(F.salutation('female'), 'Ms.');
  assert.equal(F.salutation('male'), 'Mr.');
  assert.equal(F.salutation('x'), 'Mx.');
  assert.equal(F.salutation('Mrs'), 'Mrs.');
});

test('list functions', () => {
  const kids = [{ Name: 'A', Age: 5, Minor: true }, { Name: 'B', Age: 20, Minor: false }, { Name: 'C', Age: 2, Minor: true }];
  assert.equal(F.count(kids), 3);
  assert.equal(F.count(kids, 'Minor'), 2);
  assert.equal(F.count(undefined), 0);
  assert.equal(F.count('single'), 1);
  assert.equal(F.sum(kids, 'Age'), 27);
  assert.equal(F.sum([1, 2, '3']), 6);
  assert.equal(F.sum(null), 0);
  assert.equal(F.any(kids, 'Minor'), true);
  assert.equal(F.all(kids, 'Minor'), false);
  assert.equal(F.all([], 'Minor'), false);
  assert.equal(F.any([true, false]), true);
  assert.equal(F.first(kids).Name, 'A');
  assert.equal(F.first(kids, 'Name'), 'A');
  assert.equal(F.last(kids, 'Name'), 'C');
  assert.equal(F.first([]), undefined);
  assert.deepEqual(F.sort(kids, 'Age').map((k) => k.Name), ['C', 'A', 'B']);
  assert.deepEqual(F.sort(kids, 'Age', 'desc').map((k) => k.Name), ['B', 'A', 'C']);
  assert.deepEqual(F.sort(kids, 'Name').map((k) => k.Name), ['A', 'B', 'C']);
  assert.deepEqual(F.sort([3, 1, 2]), [1, 2, 3]);
  assert.deepEqual(F.sort(['2026-02-01', '2025-12-31']), ['2025-12-31', '2026-02-01']);
  assert.deepEqual(F.filter(kids, 'Minor').map((k) => k.Name), ['A', 'C']);
  assert.deepEqual(F.filter(kids, 'Name', 'b').map((k) => k.Name), ['B']);
  assert.deepEqual(F.filter(kids, 'Age', 20).map((k) => k.Name), ['B']);
  assert.deepEqual(F.list(1, 2, 3), [1, 2, 3]);
  assert.deepEqual(F.map(kids, 'Name'), ['A', 'B', 'C']);
  assert.deepEqual(F.unique([1, 1, 2]), [1, 2]);
  assert.deepEqual(F.reverse([1, 2]), [2, 1]);
  assert.equal(F.find(kids, 'Name', 'C').Age, 2);
  assert.equal(F.group(kids, 'Minor').length, 2);
});

test('logic helpers', () => {
  assert.equal(F.default(undefined, 'x'), 'x');
  assert.equal(F.default('', 'x'), 'x');
  assert.equal(F.default(0, 'x'), 0);
  assert.equal(F.default('v', 'x'), 'v');
  assert.equal(F.coalesce(undefined, '', null, 'a', 'b'), 'a');
  assert.equal(F.coalesce(), '');
  assert.equal(F.isEmpty(''), true);
  assert.equal(F.isEmpty([]), true);
  assert.equal(F.isEmpty('a'), false);
  assert.equal(F.if(true, 'a', 'b'), 'a');
  assert.equal(F.if(0, 'a', 'b'), 'b');
  assert.equal(F.if(false, 'a'), '');
});

test('registerFunction adds a custom filter usable in expressions', () => {
  registerFunction('shout', (s) => String(s ?? '').toUpperCase() + '!');
  assert.equal(evaluate('Name|shout', { Name: 'hi' }), 'HI!');
  assert.equal(evaluate('SHOUT(Name)', { Name: 'hi' }), 'HI!');
  assert.throws(() => registerFunction('bad', 'not a fn'), TypeError);
});

test('value methods table is defensive', () => {
  assert.equal(methods.toUpperCase(undefined), '');
  assert.equal(methods.toInt('abc'), '');
  assert.deepEqual(methods.split('a,b'), ['a', 'b']);
  assert.equal(methods.first('hello', 2), 'he');
  assert.equal(methods.last('hello', 2), 'lo');
});
